// flow-typed signature: da479d0de812ebc1243331a9112b0a09
// flow-typed version: <<STUB>>/nested-error-stacks_v2.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nested-error-stacks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nested-error-stacks' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'nested-error-stacks/index' {
  declare module.exports: $Exports<'nested-error-stacks'>
}
declare module 'nested-error-stacks/index.js' {
  declare module.exports: $Exports<'nested-error-stacks'>
}
