// flow-typed signature: c153ef7bee7367771c71e9be35659133
// flow-typed version: <<STUB>>/sorted-json-stringify_v0.1.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sorted-json-stringify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sorted-json-stringify' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sorted-json-stringify/index.min' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/rollup.config' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/src/ast_to_json' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/src/index' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/src/lined_json_to_ast' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/test/base' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/test/deep_equality' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/test/order' {
  declare module.exports: any
}

declare module 'sorted-json-stringify/test/space' {
  declare module.exports: any
}

// Filename aliases
declare module 'sorted-json-stringify/index' {
  declare module.exports: $Exports<'sorted-json-stringify'>
}
declare module 'sorted-json-stringify/index.js' {
  declare module.exports: $Exports<'sorted-json-stringify'>
}
declare module 'sorted-json-stringify/index.min.js' {
  declare module.exports: $Exports<'sorted-json-stringify/index.min'>
}
declare module 'sorted-json-stringify/rollup.config.js' {
  declare module.exports: $Exports<'sorted-json-stringify/rollup.config'>
}
declare module 'sorted-json-stringify/src/ast_to_json.js' {
  declare module.exports: $Exports<'sorted-json-stringify/src/ast_to_json'>
}
declare module 'sorted-json-stringify/src/index.js' {
  declare module.exports: $Exports<'sorted-json-stringify/src/index'>
}
declare module 'sorted-json-stringify/src/lined_json_to_ast.js' {
  declare module.exports: $Exports<'sorted-json-stringify/src/lined_json_to_ast'>
}
declare module 'sorted-json-stringify/test/base.js' {
  declare module.exports: $Exports<'sorted-json-stringify/test/base'>
}
declare module 'sorted-json-stringify/test/deep_equality.js' {
  declare module.exports: $Exports<'sorted-json-stringify/test/deep_equality'>
}
declare module 'sorted-json-stringify/test/order.js' {
  declare module.exports: $Exports<'sorted-json-stringify/test/order'>
}
declare module 'sorted-json-stringify/test/space.js' {
  declare module.exports: $Exports<'sorted-json-stringify/test/space'>
}
